# Basic Information 
title: Yingying Li
position: Assistant Professor
affiliation: University of Illinois Urbana-Champaign
affiliation_link: https://ise.illinois.edu/
email: yl101 (at) illinois.edu

# Search Engine Optimization (SEO)
keywords: yaoyao liu, liu yaoyao, yaoyaoliu, liuyaoyao
canonical: https://www.cs.jhu.edu/~yyliu/
description: Yaoyao Liu is a postdoctoral fellow at Johns Hopkins University. His research lies in meta-learning, incremental learning, and image generation.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com/citations?hl=en&user=-b9PTaUAAAAJ
#cv_link: https://files.yliu.me/Yaoyao_Liu_Curriculum_Vitae.pdf
#github_link: https://github.com/yaoyao-liu/
#linkedin: https://www.linkedin.com/in/liuyaoyao/
#twitter: https://twitter.com/YaoyaoLiu1/

# Images 
avatar: ./images/yingying_li.jpg
favicon: ./images/favicon.ico
favicon_dark: ./images/favicon.ico

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
