title: Yingying Li
position: Postdoc
affiliation: UIUC
email: yl101 (at) illinois.edu
keywords: yingying li, li yingying
favicon: ./images/favicon.png
favicon_dark: ./images/favicon.png
description: Yingying Li is currently a postdoc affiliated with the Coordinated Science Laboratory at the University of Illinois Urbana-Champaign (UIUC). Her research lies in online learning, multi-armed bandit, reinforcement learning, decentralized control, and mechanism design with applications in smart grid.
canonical: https://yingyingli.web.illinois.edu/
remote_theme: yaoyao-liu/minimal-light
