# Basic Information 
title: Yingying Li
position: Postdoc
affiliation: California Institute of Technology
affiliation_link: https://www.cms.caltech.edu/
department: Computing + Mathematical Sciences Department
department_link: https://www.cms.caltech.edu/
email1: yingli2 (at) caltech.edu
email2: yl101 (at) illinois.edu
email3: yingyingli.gh (at) gmail.com
address: Annenberg Center for Information Science and Technology, 330 S Chester Ave, Pasadena, CA 91125

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Yingying Li
description: Yingying Li is currently a postdoc in the Department of Computing and Mathematical Sciences at the California Institute of Technology. Her research lies in online learning, multi-armed bandit, reinforcement learning, decentralized control, and mechanism design with applications in smart grid.
canonical: https://yingying.li/

# Links 
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?hl=en&user=-b9PTaUAAAAJ
# resume: https://yingyingli.web.illinois.edu/files/CV_Yingying_new.pdf

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/yingying_li.jpg
favicon: ./assets/img/favicon-caltech.png
favicon_dark: ./assets/img/favicon-caltech.png

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

